[package]
name = "dbgif-server"
version = "0.1.0"
edition = "2021"

[features]
default = []
transport-debug = []
full-debug = ["transport-debug"]

[dependencies]
bytes = "1.5"
crc32fast = "1.3"
anyhow = "1.0"
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rusb = "0.9"
async-trait = "0.1"
futures = "0.3"