edition = "2021"
max_width = 100
use_small_heuristics = "Max"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_impl_items = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
comment_width = 100